---
- hosts: kubeworker
  vars_files:
  - env_variables
  tasks:
  
  - name: join cluster	
    shell: "{{ hostvars['kubemaster'].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt

